services:
  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - backend_network
  webserver:
    image: nginx:1.27.0-alpine3.19-slim 
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - backend_network
  certbot:
    image: certbot/certbot:v2.11.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - backend_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend_network
    depends_on:
      - redis

networks:
  backend_network:
