services:
  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      - backend_network
    ports:
      - 6379:6379
  webserver:
    image: nginx:1.27.0-alpine3.19-slim 
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - backend_network
  certbot:
    image: certbot/certbot:v2.11.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - backend_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend_network
    depends_on:
      - redis
  db:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5000:5432
    volumes:
      - ./vol/data/postgres:/var/lib/postgresql/data

networks:
  backend_network:
